version: '3'

services:
  database_app:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  rails_app:
      depends_on:
        - 'database_app'
      build: .
      command: bash run_server.sh
      stdin_open: true
      tty: true
      ports:
        - '3000:3000'
      volumes:
        - '.:/desafio-back-end'
        - gems:/gems
  
  redis:
    image: "redis:5.0.5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  jobs:
    depends_on:
      - "database_app"
      - "redis"
      - "rails_app"
    build: .
    command: bash sidekiq
    volumes:
      - .:/desafio-back-end

volumes:
  postgres:
  gems:
  redis:
