version: '3'

services:
  database:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  
  redis:
    image: "redis:5.0.5-alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis:/var/lib/redis/data

  rails_app:
    depends_on:
      - 'database'
    build: .
    command: bash run_server.sh
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - '.:/desafio-back-end'

  jobs:
    depends_on:
      - "database"
      - "redis"
      - "rails_app"
    build: .
    command: bash run_jobs.sh
    volumes:
      - .:/desafio-back-end

volumes:
  redis:
  postgres: