default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database_app
  username: postgres
development:
  <<: *default
  database: blu-desafio-back-end_development
test:
  <<: *default
  database: blu-desafio-back-end_test
production:
  <<: *default
  database: blu-desafio-back-end_production
  username: blu-desafio-back-end
  password: <%= ENV['BLU-DESAFIO-BACK-END_DATABASE_PASSWORD'] %>
