TypeTransaction.create(id: 1, description: 'Débito', nature: 'entrada', signal: true)
TypeTransaction.create(id: 2, description: 'Boleto', nature: 'saida', signal: false)
TypeTransaction.create(id: 3, description: 'Financiamento', nature: 'saida', signal: false)
TypeTransaction.create(id: 4, description: 'Crédito', nature: 'entrada', signal: true)
TypeTransaction.create(id: 5, description: 'Recebimento Empréstimo', nature: 'entrada', signal: true)
TypeTransaction.create(id: 6, description: 'Vendas', nature: 'entrada', signal: true)
TypeTransaction.create(id: 7, description: 'Recebimento TED', nature: 'entrada', signal: true)
TypeTransaction.create(id: 8, description: 'Recebimento DOC', nature: 'entrada', signal: true)
TypeTransaction.create(id: 9, description: 'Aluguel', nature: 'saida', signal: false)