TransactionValue.delete_all
TypeTransaction.create(type: 1, description: "Débito", nature: "entrada", signal: "+")
TypeTransaction.create(type: 2, description: "Boleto", nature: "saida", signal: "-")
TypeTransaction.create(type: 3, description: "Financiamento", nature: "saida", signal: "-")
TypeTransaction.create(type: 4, description: "Crédito", nature: "entrada" signal: "+")
TypeTransaction.create(type: 5, description: "Recebimento Empréstimo", nature: "entrada", signal: "+")
TypeTransaction.create(type: 6, description: "Vendas", nature: "entrada" signal: "+")
TypeTransaction.create(type: 7, description: "Recebimento TED", nature: "entrada", signal: "+")
TypeTransaction.create(type: 8, description: "Recebimento DOC", nature: "entrada" signal: "+")
TypeTransaction.create(type: 9, description: "Aluguel", nature: "saida", signal: "-")